### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by SidTheEngineer** [carcarese/bwa-u3-jammming-prj#1]
**Project Will Need to be Re-uploaded**
Hey there, we'll need to have the entirety of the project uploaded to form a full review. Right now, it seems that only the `src` folder has been uploaded to Github.

**Comment by carcarese** [comment]
How do I do that?  When I try to select the entire project folder I get an error that it's too big to upload.

**Comment by carcarese** [comment]
I've never worked in GitHub before and need a little guidance related to how to use it.

**Comment by SidTheEngineer** [comment]
This may be due to the `node_modules` folder being included. Feel free to delete this folder before uploading if it's trying to upload with the project

**Comment by carcarese** [comment]
Yes, that appears to have solved the upload issue.  I re-submitted.  Thank you.
